5/27/2014 8:38:47 PM
Analysis of W:\TFPGADAT\HNOS~KZ9.DAT
Data set contains genotypes of individuals sampled from populations.
Organism Type: Diploid
Marker Type: Dominant
H-W Equilibrium Assumed.
Allele frequencies estimated based on the square root
of the frequency of the null (recessive) genotype.
Allele frequencies rounded to exactly match observed sample


F-STATISTICS



OVER ALL LOCI
              theta
              0.5942


 95 % C.I. from
bootstrapping over loci.

replications performed: 1000 

              theta P
Upper         0.6389
Lower         0.5460

