5/27/2014 5:03:02 PM
Analysis of W:\TFPGADAT\BIMK~MI7.DAT
Data set contains genotypes of individuals sampled from populations.
Organism Type: Diploid
Marker Type: Dominant
H-W Equilibrium Assumed.
Allele frequencies estimated based on the square root
of the frequency of the null (recessive) genotype.
Allele frequencies rounded to exactly match observed sample


F-STATISTICS



OVER ALL LOCI
              theta
              0.5325


 95 % C.I. from
bootstrapping over loci.

replications performed: 1000 

              theta P
Upper         0.5761
Lower         0.4902

